### ISSUE TITLE
install-referrer for cocos2d-x - android - eclipse project

### ISSUE THREAD

**Issue by mostafa88** [adjust/cocos2dx_sdk#28]
Hi,
Thanks for your good documentations about sdk integration for any platform. I'm using Cocos2D-x project and building an android game using Eclipse IDE. In the [Install referrer
](https://github.com/adjust/cocos2dx_sdk/blob/master/doc/android/android.md#install-referrer) part you mention using gradle, but there is no gradle when using eclispe. So please fix this in document.
Thanks.

**Comment by uerceg** [comment]
Hi @mostafa88 

Thanks for the suggestion. Nowdays Cocos2d-x doesn't even generate project for Eclipse anymore (`proj.android` is now Android Studio project by default), so Eclipse documentation got outdated. We are not even testing things in Cocos2d-x with Eclipse anymore, since Android Studio is the IDE which we officially support and work with.

Never the less, we are preparing Cocos2d-x README update with upcoming v4.14.0 and even though it will be fully Android Studio oriented, we will try to add notes for Eclipse in chapters which might not be applicable for Eclipse users. Will ping you in here once it's done and in case you notice that instructions can be improved and made better in some way for Eclipse users, feel free to suggest changes to us or even open PR with those changes.

Cheers

**Comment by uerceg** [comment]
Hi @mostafa88 

Cocos2d-x repository now has unified README and contains instructions for all supported Cocos2d-x platforms at one place (iOS and Android). Android Studio is official IDE we support and write instructions for. We have tried to write Eclipse instructions in chapters where Eclipse users would need to do something different than Android Studio folks - adding Google Play Services and install referrer libraries.

Having in mind that you (unlike us) are using Eclipse as your primary IDE, please feel free to take a look and in case you think instructions should be extended/updated/changed, feel free to submit PR with changes, we will be more than happy to review it and add to our repo.

Looking forward to hear you feedback on this topic.

Cheers
