### ISSUE TITLE
_

### ISSUE THREAD

**Issue by gleyba** [adjust/cocos2dx_sdk#4]

**Comment by nonelse** [comment]
Hi. Thanks for the feedback, we are always looking for improving our SDK.
It may show that is not best approach, but it was the best solution with the knowledge we had.
![alt text](http://m.memegen.com/u5sb1y.jpg "It's ok to now know")

Because we want it to make our SDK the best possible, we are interested in your opinion.
Can you make a PR with an example of an Pimpl Idiom with just one method? Even if it's incomplete, it would help to understand the concept.

We knew that it's possible to integrate the native SDKs directly in cocos2dx without the need of this specific SDK. But we wanted to provide some of the boilerplate needed for such task. How different would the manual/implementation be, to prevent such "problems and rage" that it currently does?

**Comment by uerceg** [comment]
Closed in https://github.com/adjust/cocos2dx_sdk/releases/tag/v4.1.0
