### ISSUE TITLE
AdjustAppStoreSubscription2dx params

### ISSUE THREAD

**Issue by tallesborges** [adjust/cocos2dx_sdk#40]
Hello, what value should I pass to the parameter `price` in the constructor of `AdjustAppStoreSubscription2dx`.

As you are receiving it as string, it is confusing me, I have some options

- Pass the localised price using `NSNumberFormatter`
- Convert float `price` from `SKProduct` to string

Can you explain what's the correct way ?

If the correct way is using `NSNumberFormatter` how it should be formatted ?

Best.

**Comment by uerceg** [comment]
Hi @tallesborges 

Sorry for the delay. In iOS case, [this](https://developer.apple.com/documentation/storekit/skproduct/1506094-price?language=objc) is what we expect to get natively. I agree that the fact that we're getting strings is not the most intuitive one, but at the end of the day, we're [converting](https://github.com/adjust/cocos2dx_sdk/blob/master/dist/ADJAppStoreSubscription2dx.mm#L17) that string back to `NSDecimalNumber`. So I'd say to simply pass value of the purchased subscription in there (I'd assume it's some double value), but converted to `std::string`.

Also for the record, in order to use subscription tracking feature, additional setup in dashboard is needed, so make sure you have that covered as well. If in doubt what and how, feel free to reach out to your dedicated account manager or to our support team (support@adjust.com).

**Comment by uerceg** [comment]
In case you have any other questions on the topic, feel free to comment/reopen. Cheers.
