### ISSUE TITLE
'jni.h' file not found

### ISSUE THREAD

**Issue by salmanqureshi** [adjust/cocos2dx_sdk#6]
First time integrating your SDK and ran into this issue. I already have the Xcode command line tools installed.
![screen shot 2015-11-12 at 12 58 52 pm](https://cloud.githubusercontent.com/assets/1450889/11113278/56a3170a-893d-11e5-8840-bd51a444e245.png)

**Comment by uerceg** [comment]
Hi @salmanqureshi 

Which version of Cocos 2d-x SDK are you integrating? I advise you always to use the latest, aka: https://github.com/adjust/cocos2dx_sdk/releases/tag/v4.1.0 at the moment.

In there we made major adjustments to our SDK. If you are using some version prior to 4.1.0 and you're developing in XCode, then you should rather only import and use files which have `ADJ-` prefix in their name. The ones starting with `Adjust-` are for Android development.

But like I said, I strongly advise you to use latest version where you won't face this kind issues, since in there we unified everything so that one common interface exists for all platforms and in there you should be able to use files starting with `Adjust-` w/o any problems no matter are you developing in XCode or Eclipse (for example).

Current `AdjustEvent2dx.h` header files starts like this:

```cpp
#if (CC_TARGET_PLATFORM == CC_PLATFORM_ANDROID)
#include <jni.h>
#elif (CC_TARGET_PLATFORM == CC_PLATFORM_IOS)
#include "ADJEvent2dx.h"
#endif
```

So, you shouldn't face this kind of build error once developing in XCode.

Please, if you are not using, update to latest Cocos 2d-x SDK version (`4.1.0`) and give it a try.

**Comment by uerceg** [comment]
@salmanqureshi Any progress on this issue?

**Comment by salmanqureshi** [comment]
Hi Uglješa,

Yes, I integrated the SDK in one of my Unity projects and said goodbye to
the cocos2d-x one for, maybe, next time.

Thanks,
-Salman

**Comment by uerceg** [comment]
:+1:
